In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('movies.csv')
df

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/lLh39Th5plbrQgbQ4zyIULsd0Pp.jpg,"[878, 28, 12]",823464,en,Godzilla x Kong: The New Empire,"고질라 X 콩, 이번에는 한 팀이다! ‘고질라’ VS ‘콩’, 두 타이탄의 전설적인...",3384.641,/4z1VMmlxHrziG45901esjB4dpIa.jpg,2024-03-27,고질라 X 콩: 뉴 엠파이어,False,6.945,1354
1,False,/tRS6jvPM9qPrrnx2KRp3ew96Yot.jpg,"[80, 9648, 53]",414906,en,The Batman,지난 2년 간 고담시의 어둠 속에서 범법자들을 응징하며 배트맨으로 살아온 브루스 웨...,516.851,/jicHGaOX5pHs7RKjfexMxvLkwjf.jpg,2022-03-01,더 배트맨,False,7.679,9562
2,False,/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg,"[35, 12]",346698,en,Barbie,원하는 무엇이든 될 수 있는 바비랜드에서 살아가던 바비가 현실 세계와 이어진 포털의...,472.981,/h3mUJ9WEJ8PzA450ad4hrjsaiqG.jpg,2023-07-19,바비,False,7.066,8232
3,False,/cjRUhKyt2Jo3V1KNzc5tpPNfccG.jpg,"[878, 28, 12]",320288,en,Dark Phoenix,어린 시절 비극적 교통사고로 능력을 알게 된 진 그레이는 자비에 영재학교에서 새로운...,439.383,/rNRfYkuRvM0z1RWHPbc2I8HCdvd.jpg,2019-06-05,엑스맨: 다크 피닉스,False,5.980,6248
4,False,/oCKZAdUROqdlTcUOstqJ1gM8JQt.jpg,"[18, 35]",615777,en,Babylon,황홀하면서도 위태로운 고대 도시 바빌론에 비유되는 할리우드에서 전성기를 누리고 있는...,378.196,/6JQtIajMe70HWtBf7uZ1ZyWiW1F.jpg,2022-12-22,바빌론,False,7.412,2786
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,/ePTcmVtDY9GxGRqiGotduti8rs3.jpg,[18],978027,fr,La Morsure,1967년 마디 그라. 프랑수아즈는 가톨릭 기숙 여학교에 다니는 열일곱 살 학생이다...,30.134,/cR75dH5etlDFORvblAMPZnp4c7U.jpg,2024-05-15,내 생의 마지막 파티,False,0.000,0
496,False,/iydo2e32277kKdITKyWLkFUhWfb.jpg,"[28, 53]",15136,cn,夕陽天使,컴퓨터 업계의 거물 초우 형제가 경영하는 회사 네트워크가 치명적인 바이러스에 감염된...,26.476,/2ZAJsAIVkpZjd2hJEvkJkD6fzDG.jpg,2002-05-14,버추얼 웨폰,False,6.800,215
497,False,/mE9TXKcVsnfDW1n7k8qrAQMwk1F.jpg,"[53, 28, 35]",791469,en,Dark Web: Cicada 3301,의문의 웹 조직에게 지능 테스트 메시지를 받은 천재 해커 ‘코너’가 그들의 정체를 ...,18.738,/xYX2NxAN5tixWAdscZYbCcmcNU9.jpg,2021-03-12,시카다 3301,False,6.100,107
498,False,/j1FMMJhWWK3im0XtnBAYm9IaEXD.jpg,"[18, 10749]",17612,en,Lost and Delirious,메리 브래드포드는 아버지가 재혼한 뒤 퍼킨즈 걸즈 콜리지에 전학 온 학생. 메리의 ...,16.220,/3Cu95A09arsfTsOJfygVwhJe5qc.jpg,2001-01-21,상실의 시대,False,6.842,476
499,False,/ax6LwhsAXesGCsBagE21DgwUYZf.jpg,[18],443463,en,Leave No Trace,"미국 오레곤주 포틀랜드 끝자락에 위치한 광활한 삼림 지역, 포레스트 파크에서 몇 년...",19.224,/w69iId8e80xBpyF0r2rfZoqRwQj.jpg,2018-06-29,흔적 없는 삶,False,6.788,1164

In [20]:
group = df.groupby('original_language')
group_size = group.size()
table = group_size.reset_index(name='cnt')

In [28]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 8))
plt.axis('off')
plt.table(cellText=table.values,
          colLabels=table.columns,
          loc='center',
         cellLoc='center',)
plt.savefig('grouped_table.png', bbox_inches='tight', pad_inches=0.5)
plt.close()

In [31]:
import dataframe_image as dfi
dfi.export(table, './table.png', max_cols=-1, max_rows=-1)

In [30]:
pip install dataframe-img

Collecting dataframe-image
  Obtaining dependency information for dataframe-image from https://files.pythonhosted.org/packages/ef/40/9e8d11ae1eb3884c6a8c150d7c7aec63079078b59cbf23581e9a156ce462/dataframe_image-0.2.3-py3-none-any.whl.metadata
  Downloading dataframe_image-0.2.3-py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: pandas>=0.24 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (2.0.3)
Requirement already satisfied: nbconvert>=5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (6.5.4)
Requirement already satisfied: aiohttp in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (3.8.5)
Requirement already satisfied: requests in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (2.31.0)
Requirement already satisfied: pillow in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (9.4.0)
Requirement already satisfied: packaging in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (23.1)
Requirement already satisfied: mistune in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (0.8.4)
Requirement already satisfied: lxml in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (4.9.3)
Requirement already satisfied: beautifulsoup4 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from dataframe-image) (4.12.2)
Collecting cssutils (from dataframe-image)
  Obtaining dependency information for cssutils from https://files.pythonhosted.org/packages/97/67/9a7e56eedd2177f468efe17cfb96eda89aa65daabb472d77f4040e585cb9/cssutils-2.11.0-py3-none-any.whl.metadata
  Downloading cssutils-2.11.0-py3-none-any.whl.metadata (8.8 kB)
Collecting html2image (from dataframe-image)
  Obtaining dependency information for html2image from https://files.pythonhosted.org/packages/89/b9/1dc02a535c71ceed5b71bd0f82e5d31fba100b59d43a35d5c40d836a8525/html2image-2.0.4.3-py3-none-any.whl.metadata
  Downloading html2image-2.0.4.3-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: bleach in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (4.1.0)
Requirement already satisfied: defusedxml in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (0.4)
Requirement already satisfied: jinja2>=3.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (3.1.2)
Requirement already satisfied: jupyter-core>=4.7 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (5.3.0)
Requirement already satisfied: jupyterlab-pygments in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (2.1.1)
Requirement already satisfied: nbclient>=0.5.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (0.5.13)
Requirement already satisfied: nbformat>=5.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (5.9.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (2.15.1)
Requirement already satisfied: tinycss2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (1.2.1)
Requirement already satisfied: traitlets>=5.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbconvert>=5->dataframe-image) (5.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from pandas>=0.24->dataframe-image) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from pandas>=0.24->dataframe-image) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from pandas>=0.24->dataframe-image) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from pandas>=0.24->dataframe-image) (1.24.3)
Requirement already satisfied: attrs>=17.3.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from aiohttp->dataframe-image) (1.2.0)
Requirement already satisfied: soupsieve>1.2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from beautifulsoup4->dataframe-image) (2.4)
Collecting websocket-client<2.0.0,>=1.0.0 (from html2image->dataframe-image)
  Obtaining dependency information for websocket-client<2.0.0,>=1.0.0 from https://files.pythonhosted.org/packages/5a/84/44687a29792a70e111c5c477230a72c4b957d88d16141199bf9acb7537a3/websocket_client-1.8.0-py3-none-any.whl.metadata
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: idna<4,>=2.5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from requests->dataframe-image) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from requests->dataframe-image) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from requests->dataframe-image) (2023.11.17)
Requirement already satisfied: platformdirs>=2.5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from jupyter-core>=4.7->nbconvert>=5->dataframe-image) (3.10.0)
Requirement already satisfied: jupyter-client>=6.1.5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe-image) (7.4.9)
Requirement already satisfied: nest-asyncio in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbclient>=0.5.0->nbconvert>=5->dataframe-image) (1.5.6)
Requirement already satisfied: fastjsonschema in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbformat>=5.1->nbconvert>=5->dataframe-image) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from nbformat>=5.1->nbconvert>=5->dataframe-image) (4.17.3)
Requirement already satisfied: six>=1.5 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.24->dataframe-image) (1.16.0)
Requirement already satisfied: webencodings in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from bleach->nbconvert>=5->dataframe-image) (0.5.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert>=5->dataframe-image) (0.18.0)
Requirement already satisfied: pyzmq>=23.0 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from jupyter-client>=6.1.5->nbclient>=0.5.0->nbconvert>=5->dataframe-image) (23.2.0)
Requirement already satisfied: tornado>=6.2 in /Users/parkjuyeon/anaconda3/lib/python3.11/site-packages (from jupyter-client>=6.1.5->nbclient>=0.5.0->nbconvert>=5->dataframe-image) (6.3.2)

Downloading dataframe_image-0.2.3-py3-none-any.whl (6.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 8.7 MB/s eta 0:00:0000:0100:01m
Downloading cssutils-2.11.0-py3-none-any.whl (398 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.2/398.2 kB 11.0 MB/s eta 0:00:00
Downloading html2image-2.0.4.3-py3-none-any.whl (27 kB)
Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 5.4 MB/s eta 0:00:00
Installing collected packages: websocket-client, cssutils, html2image, dataframe-image
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 0.58.0
    Uninstalling websocket-client-0.58.0:
      Successfully uninstalled websocket-client-0.58.0
Successfully installed cssutils-2.11.0 dataframe-image-0.2.3 html2image-2.0.4.3 websocket-client-1.8.0
Note: you may need to restart the kernel to use updated packages.

In [34]:
df2 = pd.read_csv('top_rated_movie.csv')
group = df.groupby('original_language')
group_size = group.size()
table = group_size.reset_index(name='cnt')

In [35]:
table

   original_language  cnt
0                 ca    1
1                 cn    3
2                 da    1
3                 de    5
4                 en  389
5                 es   14
6                 fa    1
7                 fr   18
8                 hi    3
9                 id    1
10                is    1
11                it    8
12                ja   28
13                ko   10
14                mk    1
15                nl    1
16                no    1
17                pl    1
18                pt    1
19                ru    1
20                sv    3
21                te    1
22                th    3
23                zh    4

In [37]:
df2 = pd.read_csv('discover_kor_movie.csv')
df2

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/x1Ex090BNIXcmaBYB2US0j3hBUF.jpg,"[28, 53, 18]",1057001,ko,The Childe,Desperate to secure funds for his mother's sur...,693.894,/ydC8ubFXQfkPJDhkduMhbE9mTz7.jpg,2023-06-21,The Childe,False,7.052,77
1,False,/8kgfR6KwCwc6WA2AY1wqBXkYpEy.jpg,"[27, 9648]",964592,ko,잠,A young couple's life is turned upside down wh...,47.926,/b4d90lpmSTLoCP9tkBU7QAQOhh0.jpg,2023-09-06,Sleep,False,6.600,66
2,False,/ji6mDx6xUAEsl65AZRrW6pWKxs4.jpg,"[35, 10749]",473924,ko,동창회의 목적: 더 비기닝,Are we dating? Even if I slept with her? Is i...,45.077,/sqJD8nD2zjRaENBsdcqwpJiSGXj.jpg,2017-02-02,Reunion Goals: The Beginning,False,8.500,6
3,False,/vblTCXOWUQGSc837vgbhDRi4HSc.jpg,"[28, 80, 35, 53]",955555,ko,범죄도시 3,Detective Ma Seok-do changes his affiliation f...,42.588,/lW6IHrtaATxDKYVYoQGU5sh0OVm.jpg,2023-05-31,The Roundup: No Way Out,False,7.000,199
4,False,/rENYZSx6HFME7YLbbY0qGYayL7F.jpg,"[9648, 18, 53]",491584,ko,버닝,An aspiring writer goes to the airport to pick...,31.006,/kXiF80o74fE9gf3Utf9moAI7ar0.jpg,2018-05-17,Burning,False,7.400,1507
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,/sKtczdCSs9us1i5zp1gvcPhpce5.jpg,[],952557,ko,프로포즈 1분위,"One day, Jung-hyeok receives a sudden proposal...",0.314,/xlWF49C6w9UMUc5tA6qWtbAtVq6.jpg,2019-10-14,How to Get Low Income,False,0.000,0
496,False,NaN,[],949363,ko,아색기가,NaN,0.216,NaN,NaN,A color of color,False,0.000,0
497,False,NaN,[],944939,ko,남의 나라,"Ahn Yong-seon, a Korean-Chinese woman was smug...",0.504,/kKRvnN7SfUZSlxfxdTMy99XIWXb.jpg,2021-10-21,Stranger's Country,False,0.000,0
498,False,NaN,[],940643,ko,패티쉬 : 흥분한 남자들,The three friends gather at Junhyung's house a...,0.216,/iTQB9qLAEOd5DWbdgeui6TP8YkR.jpg,2021-01-01,Fetish: Horny Guys,False,0.000,0
499,False,/nfspvGfcruYMifohdT5PqBbaK0S.jpg,[16],939812,ko,만도와 크레파스,NaN,0.216,/6lj6EIRgiRNn0Ac9JbveKh4mwp8.jpg,1998-01-01,만도와 크레파스,False,0.000,0